version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Redis Configuration
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0

      # Rate Limiter Configuration
      - RATE_LIMITER_IP_MAX_REQUESTS=10
      - RATE_LIMITER_IP_BLOCK_DURATION=5m
      - RATE_LIMITER_TOKEN_MAX_REQUESTS=100
      - RATE_LIMITER_TOKEN_BLOCK_DURATION=1h
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
